/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorAccionCursos;
import java.awt.Color;
import modelo.RegistroCursos;

/**
 *
 * @author Diego
 */
public class GuiAccionesCursos extends javax.swing.JFrame {

    /**
     * Creates new form GuiAccionesCursos
     */
    private ManejadorAccionCursos manejadorAccionCursos;
    public GuiAccionesCursos() {
        initComponents();
        getContentPane().setBackground(Color.BLACK);
    }
    public void init(RegistroCursos registroCursos)
    {
        manejadorAccionCursos= new ManejadorAccionCursos(this, panelBotonesSeleccion1, registroCursos);
        panelBotonesSeleccion1.setManejador(manejadorAccionCursos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonesSeleccion1 = new vista.PanelBotonesSeleccion();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(panelBotonesSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotonesSeleccion1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelBotonesSeleccion panelBotonesSeleccion1;
    // End of variables declaration//GEN-END:variables
}
