/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorAccionCursos;
import controlador.ManejadorAccionEstudiante;
import java.awt.Color;
import modelo.Estudiante;
import modelo.RegistroCursos;
import modelo.RegistroEstudiante;

/**
 *
 * @author Diego
 */
public class GuiAccionesEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form GuiRegistroEstudiante
     */
    private ManejadorAccionEstudiante manejadorEstudiante;
    private RegistroEstudiante registroEstudiante;
    //private Object panelBotonesAccion;
    public GuiAccionesEstudiante() {
        initComponents();
        super.getContentPane().setBackground(Color.BLACK);
        setTitle("CONTROL DE ESTUDIANTES");  
    }

    public void init(RegistroEstudiante registroEstudiante)
    {
        manejadorEstudiante= new ManejadorAccionEstudiante(panelBotonesSeleccion1, this,registroEstudiante);
        
        panelBotonesSeleccion1.setManejador(manejadorEstudiante);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonesSeleccion1 = new vista.PanelBotonesSeleccion();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(panelBotonesSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(160, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBotonesSeleccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.PanelBotonesSeleccion panelBotonesSeleccion1;
    // End of variables declaration//GEN-END:variables

}
