/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorConsultaEstudiante;
import java.awt.Color;
import javax.swing.JRadioButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import modelo.RegistroEstudiante;

/**
 *
 * @author Diego
 */
public class GuiConsultarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form GuiConsultarEstudiante
     */
    private  ManejadorConsultaEstudiante manejadorConsultaEstudiante;
    public GuiConsultarEstudiante() {
        initComponents();
        getContentPane().setBackground(Color.white);
        panelBotonesAccion1.getBotonAceptar();
        jTecarnet.setEditable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupConsulta = new javax.swing.ButtonGroup();
        panelBotonesAccion1 = new vista.PanelBotonesAccion();
        jRespecifico = new javax.swing.JRadioButton();
        jRgeneral = new javax.swing.JRadioButton();
        jLopciones = new javax.swing.JLabel();
        jTecarnet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta De Estudiantes");

        buttonGroupConsulta.add(jRespecifico);
        jRespecifico.setText("Consulta Especifica");

        buttonGroupConsulta.add(jRgeneral);
        jRgeneral.setText("Consulta General");
        jRgeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRgeneralActionPerformed(evt);
            }
        });

        jLopciones.setText("Opciones ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLopciones)
                            .addComponent(jRgeneral)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRespecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLopciones, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRespecifico)
                    .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRgeneral)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRgeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRgeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRgeneralActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupConsulta;
    private javax.swing.JLabel jLopciones;
    private javax.swing.JRadioButton jRespecifico;
    private javax.swing.JRadioButton jRgeneral;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTecarnet;
    private javax.swing.JTextArea jTextArea1;
    private vista.PanelBotonesAccion panelBotonesAccion1;
    // End of variables declaration//GEN-END:variables
public void init(RegistroEstudiante registroEstudiante)
{
    manejadorConsultaEstudiante= new ManejadorConsultaEstudiante(registroEstudiante, this, panelBotonesAccion1);
    panelBotonesAccion1.setManejador(manejadorConsultaEstudiante);  
    jRespecifico.addActionListener(manejadorConsultaEstudiante);
    jRgeneral.addActionListener(manejadorConsultaEstudiante);
    
}
public void limpiarCampos(String titulos [])
{
    jTecarnet.setText("");
    jTable1.setModel(new DefaultTableModel(null, titulos));
}
public JTextField getCarnet()
{
    
    return jTecarnet;
}
public JRadioButton getJRadioEspecifico()
{
    return jRespecifico;
}
public JRadioButton getJRadioGeneral()
{
    return jRgeneral;
}
public JTextArea getArea()
{
return jTextArea1;
}
public void setDatosTabla(String datos [][],String titulos[])
{
    jTable1.setModel(new DefaultTableModel(datos, titulos));
}

}
