/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorEliminarEstudiante;
import javax.swing.JTextArea;
import modelo.RegistroEstudiante;

/**
 *
 * @author Diego
 */
public class GuiEliminarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form GuiEliminarEstudiante
     */
    private ManejadorEliminarEstudiante manejadorEliminarEstudiante;
    public GuiEliminarEstudiante() {
        initComponents();
        setTitle("Eliminar Un Estudiante");
        
    }

    public void init(RegistroEstudiante registroEstudiante)
    {
        manejadorEliminarEstudiante= new ManejadorEliminarEstudiante(panelBotonesAccion1, this,registroEstudiante);
        panelBotonesAccion1.setManejador(manejadorEliminarEstudiante);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonesAccion1 = new vista.PanelBotonesAccion();
        jLcarnet = new javax.swing.JLabel();
        jTecarnet = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTinformacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLcarnet.setText("Carnet");

        jTinformacion.setEditable(false);
        jTinformacion.setColumns(20);
        jTinformacion.setRows(5);
        jTinformacion.setEnabled(false);
        jTinformacion.setOpaque(false);
        jScrollPane1.setViewportView(jTinformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLcarnet)
                        .addGap(18, 18, 18)
                        .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLcarnet)
                            .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLcarnet;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTecarnet;
    private javax.swing.JTextArea jTinformacion;
    private vista.PanelBotonesAccion panelBotonesAccion1;
    // End of variables declaration//GEN-END:variables
public void limpiarCampos()
{
    jTecarnet.setText("");
    
}
public String getCarnet()
{
    return jTecarnet.getText().trim();
}
public JTextArea getAreaDeTexto()
{
    return jTinformacion;
}
}
