/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorModificarEstudiante;
import java.awt.Color;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.RegistroEstudiante;

/**
 *
 * @author Diego
 */
public class GuiModificarEstudiante extends javax.swing.JFrame {

    /**
     * Creates new form GuiModificarEstudiante
     */
    public static  final String BOTON_BUSCAR="Buscar";
    public GuiModificarEstudiante() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setTitle("Modificacion De Un Estudiante");
        panelBotonesAccion1.getBotonAceptar();
    }

    public void init(RegistroEstudiante registroEstudiante)
    {
        jBbuscar.setText(BOTON_BUSCAR);
        ManejadorModificarEstudiante manejadorModificarEstudiante= new ManejadorModificarEstudiante(registroEstudiante, this, panelBotonesAccion1);
        panelBotonesAccion1.setManejador(manejadorModificarEstudiante);
        jBbuscar.addActionListener(manejadorModificarEstudiante);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBbuscar = new javax.swing.JButton();
        panelBotonesAccion1 = new vista.PanelBotonesAccion();
        jLcarnet = new javax.swing.JLabel();
        jLnombre = new javax.swing.JLabel();
        jTcarnet = new javax.swing.JTextField();
        jTnombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTeinformacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modifiicacion De Un Estudiante");
        setBackground(new java.awt.Color(204, 255, 204));

        jBbuscar.setText("Buscar");

        jLcarnet.setText("Carnet");

        jLnombre.setText("Nombre");

        jTeinformacion.setEditable(false);
        jTeinformacion.setColumns(20);
        jTeinformacion.setRows(5);
        jTeinformacion.setOpaque(false);
        jScrollPane1.setViewportView(jTeinformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLcarnet)
                        .addGap(18, 18, 18)
                        .addComponent(jTcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBbuscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLnombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLcarnet)
                    .addComponent(jTcarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBbuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLnombre)
                            .addComponent(jTnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBbuscar;
    private javax.swing.JLabel jLcarnet;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTcarnet;
    private javax.swing.JTextArea jTeinformacion;
    private javax.swing.JTextField jTnombre;
    private vista.PanelBotonesAccion panelBotonesAccion1;
    // End of variables declaration//GEN-END:variables

public void limpiarCampos()
{
    jTcarnet.setText("");
    jTnombre.setText("");
}
public JTextField getCarnet()
{
    return jTcarnet;
}
public JTextField getNombre()
{
    return jTnombre;
}
public JTextArea getAreaDeInformacion()
{
    return jTeinformacion;
}
}
