/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorMatricula;
import javax.swing.JComboBox;
import javax.swing.JTextArea;
import modelo.Matricula;
import modelo.RegistroCursos;
import modelo.RegistroEstudiante;
import modelo.RegistroMatricula;

/**
 *
 * @author Diego
 */
public class GuiMatricula extends javax.swing.JFrame {

    /**
     * Creates new form GuiMatricula
     */
    private ManejadorMatricula manejadorMatricula;
    private RegistroMatricula registroMatricula;
    public static  final String BOTON_AGREGAR="Agregar";
    public GuiMatricula() {
        initComponents();
        
       // registroMatricula.AgregarItemCombos(this);
    }

    public void init(RegistroMatricula registroMatricula)
    {
       jBuagregar.setText(BOTON_AGREGAR);
       manejadorMatricula= new ManejadorMatricula(this, panelBotonesAccion1, registroMatricula);
       panelBotonesAccion1.setManejador(manejadorMatricula);
       jBuagregar.addActionListener(manejadorMatricula);
       registroMatricula.AgregarItemCombos(this);
       
    }
    public JComboBox getComboCursos()
    {
        return jComboCursos;
    }
    public JComboBox getComboEstudiantes()
    {
        return jComboEstudiantes;
    }
    public JTextArea getArea()
    {
        return jTexArea;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotonesAccion1 = new vista.PanelBotonesAccion();
        jBuagregar = new javax.swing.JButton();
        jLestudiantes = new javax.swing.JLabel();
        jLcursos = new javax.swing.JLabel();
        jComboCursos = new javax.swing.JComboBox();
        jComboEstudiantes = new javax.swing.JComboBox();
        panelTablaInformacion1 = new vista.PanelTablaInformacion();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTexArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBuagregar.setText("Agregar");

        jLestudiantes.setText("Estudiantes");

        jLcursos.setText("Cursos ");

        jComboCursos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboEstudiantes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTexArea.setEditable(false);
        jTexArea.setColumns(20);
        jTexArea.setRows(5);
        jTexArea.setEnabled(false);
        jTexArea.setOpaque(false);
        jScrollPane1.setViewportView(jTexArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTablaInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBuagregar))
                    .addComponent(jLcursos)))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLestudiantes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(227, 227, 227))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLcursos)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBuagregar)
                            .addComponent(jComboCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panelTablaInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLestudiantes)
                        .addGap(12, 12, 12)
                        .addComponent(jComboEstudiantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBuagregar;
    private javax.swing.JComboBox jComboCursos;
    private javax.swing.JComboBox jComboEstudiantes;
    private javax.swing.JLabel jLcursos;
    private javax.swing.JLabel jLestudiantes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTexArea;
    private vista.PanelBotonesAccion panelBotonesAccion1;
    private vista.PanelTablaInformacion panelTablaInformacion1;
    // End of variables declaration//GEN-END:variables

public void limpiar(String datosFilas[][],String datosColumna[])
{
    panelTablaInformacion1.setDatosTabla(datosFilas, datosColumna);
    jTexArea.setText("");
}
 public void setDatosTabla(String datosFilas[][],String datosColumna[])
{
    panelTablaInformacion1.setDatosTabla(datosFilas, datosColumna);
} 
}
