/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorAccionEstudiante;
import controlador.ManejadorRegisrtroEstudiantes;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import modelo.Estudiante;
import modelo.RegistroEstudiante;

/**
 *
 * @author Diego
 */
public class GuiRegistroEstudiantes extends javax.swing.JFrame {

    /**
     * Creates new form GuiRegistroCursos
     */
    private ManejadorRegisrtroEstudiantes manejador;
    public GuiRegistroEstudiantes() {
        initComponents();
        getContentPane().setBackground(Color.white);
        setTitle("Registar Nuevo Estudiante");
        
    }

    public void init(RegistroEstudiante registroEstudiante)
    {
        manejador= new ManejadorRegisrtroEstudiantes(panelBotonesAccion1, this,registroEstudiante);
        panelBotonesAccion1.setManejador(manejador);  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnombre = new javax.swing.JLabel();
        jLcarnet = new javax.swing.JLabel();
        jTenombre = new javax.swing.JTextField();
        jTecarnet = new javax.swing.JTextField();
        panelBotonesAccion1 = new vista.PanelBotonesAccion();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTinformacion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLnombre.setText("Nombre");

        jLcarnet.setText("Carnet");

        jTinformacion.setEditable(false);
        jTinformacion.setColumns(20);
        jTinformacion.setRows(5);
        jTinformacion.setEnabled(false);
        jTinformacion.setOpaque(false);
        jScrollPane1.setViewportView(jTinformacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLnombre)
                            .addComponent(jLcarnet))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTenombre, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLnombre)
                            .addComponent(jTenombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLcarnet)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelBotonesAccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLcarnet;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTecarnet;
    private javax.swing.JTextField jTenombre;
    private javax.swing.JTextArea jTinformacion;
    private vista.PanelBotonesAccion panelBotonesAccion1;
    // End of variables declaration//GEN-END:variables

public void limpiarCampos()
{
    jTecarnet.setText("");
    jTenombre.setText("");
}
public String getCarnet()
{
    return jTecarnet.getText();
}

public String getNombre()
{
    return jTenombre.getText();
}
public Estudiante getEstudiante()
{
    Estudiante estudiante = new Estudiante(jTecarnet.getText(), jTenombre.getText());
    return estudiante;
}
public JTextArea getAreaDeTexto()
{
    return jTinformacion;
}
public boolean verificarCamposVacios()
{
    boolean exitenCamposVacios=true;
    if(!jTecarnet.getText().trim().equalsIgnoreCase("")&&!jTenombre.getText().trim().equalsIgnoreCase(""))
    {
        exitenCamposVacios=false;
    }
    return exitenCamposVacios;
}
}
