/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ManejadorReporte;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import modelo.RegistroEstudiante;
import modelo.RegistroMatricula;

/**
 *
 * @author Diego
 */
public class GuiReporte extends javax.swing.JFrame {

    /**
     * Creates new form GuiReporte
     */
    public static final String BOTON_ACEPTAR="Aceptar";
    private ManejadorReporte manejadorReporte;
    public GuiReporte() {
        initComponents();
        jButton1.setText(BOTON_ACEPTAR);
    }
    public void init(RegistroMatricula registroMatricula,RegistroEstudiante registroEstudiante)
    {
        manejadorReporte= new ManejadorReporte(this,registroMatricula, registroEstudiante);
        
        jButton1.addActionListener(manejadorReporte);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLcarnet = new javax.swing.JLabel();
        jTecarnet = new javax.swing.JTextField();
        panelTablaInformacion1 = new vista.PanelTablaInformacion();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLcreditos = new javax.swing.JLabel();
        jTecreditos = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLfecha = new javax.swing.JLabel();
        jLadatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLcarnet.setText("Carnet");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jLcreditos.setText("Total Creditos");

        jTecreditos.setEditable(false);
        jTecreditos.setOpaque(false);

        jButton1.setText("Buscar");

        jLfecha.setText("Fecha:");

        jLadatos.setText("l");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTablaInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLcreditos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTecreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLfecha)
                        .addGap(18, 18, 18)
                        .addComponent(jLadatos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLcarnet)
                        .addGap(18, 18, 18)
                        .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLcarnet)
                            .addComponent(jTecarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelTablaInformacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLcreditos)
                            .addComponent(jTecreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLfecha)
                            .addComponent(jLadatos))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLadatos;
    private javax.swing.JLabel jLcarnet;
    private javax.swing.JLabel jLcreditos;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTecarnet;
    private javax.swing.JTextField jTecreditos;
    private javax.swing.JTextArea jTextArea1;
    private vista.PanelTablaInformacion panelTablaInformacion1;
    // End of variables declaration//GEN-END:variables
public JTextArea areaTexto()
{
    return jTextArea1;
}

public JTextField getCarnet()
{
    return jTecarnet;
}
public JTextField getCreditos()
{
    return jTecreditos;
}
public JLabel getFecha()
{
    return jLadatos;
}
public void setDatosTabla(String datos [][],String titulos[])
{
    panelTablaInformacion1.setDatosTabla(datos, titulos);
}
}
