/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author Diego
 */
public class PanelBotonesAccion extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotonesAccion
     */
    public static final String BOTON_ACEPTAR="Aceptar";
    public static final String BOTON_CANCELAR="Cancelar";
    public PanelBotonesAccion() {
        initComponents();
        jBaceptar.setText(BOTON_ACEPTAR);
        jBcancelar.setText(BOTON_CANCELAR);
    }
    public void setManejador(ActionListener manejadorBotones)
    {
        jBaceptar.addActionListener(manejadorBotones);
        jBcancelar.addActionListener(manejadorBotones);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBaceptar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();

        setFocusTraversalPolicyProvider(true);

        jBaceptar.setText("Aceptar");

        jBcancelar.setText("Cancelar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBaceptar)
                .addGap(63, 63, 63)
                .addComponent(jBcancelar))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBaceptar)
                    .addComponent(jBcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBaceptar;
    private javax.swing.JButton jBcancelar;
    // End of variables declaration//GEN-END:variables

public JButton getBotonAceptar()
{
    jBaceptar.setEnabled(false);
    return jBaceptar;
}
}
